# Generated by Django 4.2.2 on 2023-07-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=50, verbose_name='Имя гостя')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email гостя')),
                ('text_records', models.TextField(blank=True, max_length=300, null=True, verbose_name='Доп. описание')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', verbose_name='Статус')),
            ],
        ),
    ]
