# Generated by Django 4.2.2 on 2023-07-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbook',
            options={'verbose_name': 'гостевая книга', 'verbose_name_plural': 'гостевая книга'},
        ),
        migrations.AlterModelTable(
            name='guestbook',
            table='guestbook',
        ),
    ]
