# Generated by Django 4.2.2 on 2023-07-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0002_alter_guestbook_options_alter_guestbook_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
