# Generated by Django 4.2.2 on 2023-07-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0003_alter_guestbook_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='text_records',
            field=models.TextField(default='default', max_length=300, verbose_name='Доп. описание'),
            preserve_default=False,
        ),
    ]
